language: node_js
node_js:
  - "5"
install:
  - npm install
  - chmod +x scripts/build.sh
script: npm run test-travis
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
